var lines = [
  {'name':'Папа', 'align': 'left-side', 'text':'Ты уже в постели?'},
  {'name':'Лина', 'align': 'right-side', 'text':'Да, пап, что случилось?'},
  {'name':'Папа', 'align': 'left-side', 'text':'Ты закрыла входную дверь?'},
  {'name':'Лина', 'align': 'right-side', 'text':'Не помню...'},
  {'name':'Лина', 'align': 'right-side', 'text':'А разве ты ещё не идёшь домой?'},
  {'name':'Папа', 'align': 'left-side', 'text':'Нет.'},
  {'name':'Папа', 'align': 'left-side', 'text':'Слушай меня внимательно...'},
  {'name':'Папа', 'align': 'left-side', 'text':'Посмотри в окно.'},
  {'name':'Папа', 'align': 'left-side', 'text':'Видишь мужчину?'},
  {'name':'Лина', 'align': 'right-side', 'text':'Ты меня пугаешь.<br>Что происходит?'},
  {'name':'Папа', 'align': 'left-side', 'text':'Посмотри скорее!'},
  {'name':'Лина', 'align': 'right-side', 'text':'О_о папа, кто это?'},
  {'name':'Папа', 'align': 'left-side', 'text':'Не спускай с него глаз!'},
  {'name':'Лина', 'align': 'right-side', 'text':'Ничего не понимаю... Зачем это?'},
  {'name':'Папа', 'align': 'left-side', 'text':'Я серьезно. Смотри, не отрываясь!'},
  {'name':'Папа', 'align': 'left-side', 'text':'И если он будет тебе писать, обещай не отвечать ему!'},
  {'name':'Лина', 'align': 'right-side', 'text':'Что?? С чего это он будет мне писать?'},
  {'name':'Папа', 'align': 'left-side', 'text':'ОБЕЩАЙ!'},
  {'name':'Лина', 'align': 'right-side', 'text':'Хорошо. Но... Тебя ведь здесь нет...'},
  {'name':'Лина', 'align': 'right-side', 'text':'Откуда ты знаешь, что он там, за окном?'},
  {'name':'Лина', 'align': 'right-side', 'text':'ПАПА?!!?!'}
/*  {'name':'Папа', 'align': 'left-side', 'text':'Неважно.'},
  {'name':'Папа', 'align': 'left-side', 'text':'Важно только то...'},
  {'name':'Папа', 'align': 'left-side', 'text':'что его нельзя упускать из вида.'},
  {'name':'Папа', 'align': 'left-side', 'text':'Пока ты будешь смотреть на него...'},
  {'name':'Папа', 'align': 'left-side', 'text':'он не сможет двигаться.'},
  {'name':'Лина', 'align': 'right-side', 'text':'Бред какой-то!'},
  {'name':'Папа', 'align': 'left-side', 'text':'И тем не менее, это правда.'},
  {'name':'Лина', 'align': 'right-side', 'text':'Что за чёрт...'},
  {'name':'Лина', 'align': 'right-side', 'text':'Я лучше пойду закроюсь в ванной. Там не страшно.'},
  {'name':'Папа', 'align': 'left-side', 'text':'НЕТ!'},
  {'name':'Лина', 'align': 'right-side', 'text':'ПОЧЕМУ НЕТ?!'},
  {'name':'Папа', 'align': 'left-side', 'text':'Там опасно.'},
  {'name':'Лина', 'align': 'right-side', 'text':'ТОГДА ПРИЕЗЖАЙ САМ СЮДА!'},
  {'name':'Лина', 'align': 'right-side', 'text':'Знаешь, это сложновато...'},
  {'name':'Лина', 'align': 'right-side', 'text':'писать тебе и одноременно смотреть на него!'},
  {'name':'Папа', 'align': 'left-side', 'text':'ТАК ПРЕКРАТИ ПИСАТЬ!!'},
  {'name':'Папа', 'align': 'left-side', 'text':'Просто смотри.'},
  {'name':'Папа', 'align': 'left-side', 'text':'Я уже собираюсь домой.'},
  {'name':'Лина', 'align': 'right-side', 'text':'Я вообще ничего не понимаю!'},
  {'name':'Папа', 'align': 'left-side', 'text':'Знаю. Прости.'},
  {'name':'Папа', 'align': 'left-side', 'text':'Просто поверь мне.'},
  {'name':'Лина', 'align': 'right-side', 'text':'Я верю. Но этот человек...'},
  {'name':'Папа', 'align': 'left-side', 'text':'Доченька, я знаю, что тебе страшно.'},
  {'name':'Лина', 'align': 'right-side', 'text':'Нет, он просто...'},
  {'name':'Лина', 'align': 'right-side', 'text':'Я на секунду отвела взгляд.'},
  {'name':'Лина', 'align': 'right-side', 'text':'И он исчез.'},
  {'name':'Папа', 'align': 'left-side', 'text':'Ты уверена?'},
  {'name':'Лина', 'align': 'right-side', 'text':'Уверена ли я...'},
  {'name':'Лина', 'align': 'right-side', 'text':'что этот ужасный человек...'},
  {'name':'Лина', 'align': 'right-side', 'text':'в жутком черном плаще...'},
  {'name':'Лина', 'align': 'right-side', 'text':'больше не смотрит в моё окно?!'}
*/
]